### ISSUE TITLE
ERROR record with no timestamp field:

### ISSUE THREAD

**Issue by halimB8** [elastic/ml-cpp#1437]
Hello, 

I am beginner with ELK ml, I am trying to use autodetect for anomaly detection, when I run the command: 
**./autodetect --jobid Test --timefield=timestamp --timeformat=yyyy-MM-dd'T'HH:mm:ss.SSSZ --input=test_sample1 --fieldname=all**

with an example of logs: 
**{"timestamp": "2020-07-23T09:45:40.685Z","_index": "packetbeat-000001","_type": "_doc","_id": "hwqKdnMBA-ktk-2146je","_version": 2,"agent": "packetbeat","remote_ip": "127.0.0.1","remote_user": "User1","request": "GET","response": "ok"}**

I get the error : 
**ERROR CDataProcessor.cc@63 Found record with no timestamp field:**

thanks for your help
(If anyone have example of commands running autodetect or supervised training it will be very helpful for me)

**Comment by droberts195** [comment]
@halimB8 we don't intend end users to run the ML processes at the command line.  Instead we expect them to be run via Elasticsearch.

The reason you get that error is that `autodetect` cannot accept JSON.  The default input format directly on the command line is tab separated values (TSV).

To use ML in the supported way, have a look at https://www.elastic.co/guide/en/machine-learning/current/ml-gs-jobs.html for anomaly detection or https://www.elastic.co/guide/en/machine-learning/current/ml-dfanalytics.html for supervised training.

**Comment by halimB8** [comment]
@droberts195 Thanks for your reply it helped me to run my command and now it's working
could you tell me please how to integrate the this repo with Elasticsearch code source 
 Thanks

**Comment by droberts195** [comment]
> could you tell me please how to integrate the this repo with Elasticsearch code source

You have to set up a directory structure like this:

```
elasticsearch
elasticsearch-extra/ml-cpp
```

In other words, the `elasticsearch-extra` directory is at the same level as `elasticsearch`, which is a clone of the `elasticsearch` repo.  Then `ml-cpp` needs to be a sub-directory of `elasticsearch-extra`.  `ml-cpp` in this structure can be a symlink to wherever you currently have it cloned, which makes things easier.

Then, when you run `./gradlew assemble` in the `elasticsearch` directory it will build the C++ locally instead of downloading a pre-built bundle from S3.  This allows you to incorporate local C++ changes into a local Elasticsearch build.
