### ISSUE TITLE
Native bundle increase in 8.0.0

### ISSUE THREAD

**Issue by benwtrent** [elastic/ml-cpp#2038]
7.x is 58mb

In 8.0.0 its 350+mb.

I am guessing this is a bunch of pytorch stuff, but it would be good to communicate why our bundle is so much larger.

**Comment by nik9000** [comment]
It looks like pytorch is ~128mb. libmkl is a lot of the rest of it:
```
-rw-r--r-- 1 nik9000 nik9000 127486824 Sep 22 14:35 libtorch_cpu.so
-rw-r--r-- 1 nik9000 nik9000  71399952 Sep 22 14:35 libmkl_core.so
-rw-r--r-- 1 nik9000 nik9000  65751824 Sep 22 14:35 libmkl_avx512_mic.so
-rw-r--r-- 1 nik9000 nik9000  62151448 Sep 22 14:35 libmkl_avx512.so
-rw-r--r-- 1 nik9000 nik9000  51131336 Sep 22 14:35 libmkl_avx.so
-rw-r--r-- 1 nik9000 nik9000  47768528 Sep 22 14:35 libmkl_avx2.so
-rw-r--r-- 1 nik9000 nik9000  40842880 Sep 22 14:35 libmkl_def.so
-rw-r--r-- 1 nik9000 nik9000  28703528 Sep 22 14:35 libmkl_gnu_thread.so
-rw-r--r-- 1 nik9000 nik9000  15299264 Sep 22 14:35 libmkl_vml_avx.so
-rw-r--r-- 1 nik9000 nik9000  14725704 Sep 22 14:35 libmkl_vml_avx512_mic.so
-rw-r--r-- 1 nik9000 nik9000  14393832 Sep 22 14:35 libmkl_vml_avx2.so
-rw-r--r-- 1 nik9000 nik9000  13941408 Sep 22 14:35 libmkl_vml_mc.so
-rw-r--r-- 1 nik9000 nik9000  13924832 Sep 22 14:35 libmkl_vml_mc3.so
-rw-r--r-- 1 nik9000 nik9000  13879968 Sep 22 14:35 libmkl_vml_mc2.so
-rw-r--r-- 1 nik9000 nik9000  13709832 Sep 22 14:35 libmkl_vml_avx512.so
-rw-r--r-- 1 nik9000 nik9000  12073688 Sep 22 14:35 libMlMaths.so
-rw-r--r-- 1 nik9000 nik9000  11619728 Sep 22 14:35 libmkl_intel_lp64.so
-rw-r--r-- 1 nik9000 nik9000   8069920 Sep 22 14:35 libmkl_vml_def.so
-rw-r--r-- 1 nik9000 nik9000   7282592 Sep 22 14:35 libmkl_vml_cmpt.so
```
That's impressive.

**Comment by rjernst** [comment]
@benwtrent Would it be possible to statically link what we use from pytorch? This is quite a big jump in size.

**Comment by benwtrent** [comment]
@droberts195 && @davidkyle are the experts here :). I know next to nothing about this.

I agree, the size is a big jump.

**Comment by droberts195** [comment]
> Would it be possible to statically link what we use from pytorch/mkl?

I don't think that statically linking PyTorch would be as simple as it sounds.  https://github.com/pytorch/pytorch/issues/21737 was a long running bug about statically linking PyTorch.  That was fixed earlier this year by https://github.com/pytorch/pytorch/pull/49458.  But if you look at the details of the fix, it is to use the `-Wl,--whole-archive` flag when linking the PyTorch static libraries.  So I don't think it will reduce the size.  It would basically cause all the `.o` files that currently get bundled into `libtorch_cpu.so` to instead get bundled into our `pytorch_inference` program.

As for MKL, there _may_ be something we can do.  One thing to know about MKL is that it contains versions of the same functions compiled for lots of different CPU instruction sets: AVX, AVX2, AVX512, none of those, etc. Then it selects the best version of the function to use at runtime, so that it works across a wide variety of CPU types but gives best possible performance given the instructions the CPU has available. So statically linking would somehow need to figure out which functions were required and then include the `.o` files for all the different versions of each function, even ones that wouldn't be used on the machine where the build was being done.  I don't know if this is possible, or, if it is, if it requires some special tooling.  We can continue to investigate that.  The MKL website suggests that you can statically link, but I don't know if that's just the outer wrapper libraries, and then you still have to ship all the instruction-specific `.so` files to have all the different function implementations.

As for the justification for the size increase (which will occur to some extent even if we succeed in getting static linking to work), it's to support advanced search use cases like semantic search.  The combination of this stuff plus [ANN in Lucene 9](https://issues.apache.org/jira/browse/LUCENE-9004) will allow Elasticsearch 8.x searches to find documents not just by looking for terms in the documents but by comparing the meaning of the search query and the meaning of the text in the documents.  Eventually (probably not in 8.0 but a later 8.x) this will be wrapped up in App Search and Workplace Search so that users get a more Google-like level of search experience.

**Comment by rjernst** [comment]
Thanks for the detailed explanation, @droberts195. It is unfortunate static linking is so difficult here. I hope one day we can utilize Java's upcoming SIMD abstractions and not need C++ to do these operations.

**Comment by davidkyle** [comment]
The space savings that come with static linking derive from not linking any functions that are not called, due to the way PyTorch is designed there is no way that saving can be made.

PyTorch is a tool to train and evaluate serialisable models, we are testing with Neural Networks but there are many different types of models that can be evaluated in PyTorch. Each model consists of data (the weights of the NN) and instructions how to evaluate the model (activation functions etc), we cannot know at build time which activation function or convolution is needed as that information is in the model so we cannot statically link a minimum set of functions, we have to include the whole thing.  

PyTorch provide pre-built binaries as dynamic libraries, they do not release static archives because basically as Dave said it would mean linking the entire thing in which case why not use the dynamic lib which can be shared between multiple programs. 

Apologies @rjernst we should have given you a heads up that the change was coming. 

The team are really excited about this change it brings NN inference to the elastic stack and we see a lot of potential.


**Note:** The size increase is different for different platforms as we do not ship MKL everywhere

|Platform|Size Increase|
|---------|------------|
| macOS x86 | 82MB| 
| macOS M1| 56MB |
| Windows x86 | 78MB|
| Linux Aarch64 | 84MB|

**Comment by jordansirwin** [comment]
From Cloud-Infra: Discussed with @benzo-elastic and we don't have any concerns with the increased image size for ESS. This is still relatively small compared to the other images we depend on.

**Comment by davidkyle** [comment]
PyTorch 1.10 contains a new `Lite Interpreter` for inference tasks which may be smaller than `libtorch`. Interestingly it supports 'custom' builds for a subset of operators, the idea is to export the list of the operators used by your model then build a custom interpreter for that subset of operators.

`Lite Interpreter` is mobile only at the moment but it is under active development and may make it to a production platform. 

https://pytorch.org/tutorials/prototype/lite_interpreter.html#how-to-use-lite-interpreter-custom-build

**Comment by droberts195** [comment]
The effect of this has been mitigated in 8.2 and above by https://github.com/elastic/elasticsearch/pull/84536
