### ISSUE TITLE
[ML] Reproducibility of incremental training results

### ISSUE THREAD

**Issue by valeriy42** [elastic/ml-cpp#2146]
After the update step, we get different results depending on whether we are searching for hyperparameters or explicitly specifying the found values in the configuration. This difference makes it impossible to analyze the impact of hyperparameters on the system in the multistep learning regime. 

Hence, we need to introduce comprehensive testing of this behavior and find the root cause of the difference.

**Comment by valeriy42** [comment]
If a hyperparameter, e.g., `alpha` is not set in the configuration, it assumes the value `0.0`, and incremental training does not search for it. This seems to be erroneous behavior. If a search range is specified, the parameter is searched within this range.

The parameters `alpha`, `gamma`, and `lambda` are scaled unless `downsample_factor` is set to 1.0 and `previous_train_num_rows` Is unset. IMO, this behavior is counterintuitive: If I specify a search range, I expect the final hyperparameter value to be within this range.

WDYT @tveasey ?

**Comment by tveasey** [comment]
> If a hyperparameter, e.g., alpha is not set in the configuration, it assumes the value 0.0, and incremental training does not search for it.

Are you sure about this? I'm pretty sure it will search for it that was certainly the intention.

>  IMO, this behavior is counterintuitive: If I specify a search range, I expect the final hyperparameter value to be within this range.

I also spent some time pondering what is the best thing to do for this. Part of the issue is we have use parameter range for both line search results and user overrides, but I think there is more to this: for example different considerations may apply for multistep versus one off retrain with very different amount of data. Let's discuss this offline.

**Comment by valeriy42** [comment]
> Are you sure about this? I'm pretty sure it will search for it that was certainly the intention.
Yes, see #2148 test in **https://github.com/elastic/ml-cpp/blob/a170edb65e27b4aac5979154e87b48973972f04d/jupyter/tests/incremental_learning/test_incremental_learning.py#L95**
