### ISSUE TITLE
Publish third party library dependencies in separate artifact

### ISSUE THREAD

**Issue by mark-vieira** [elastic/ml-cpp#2158]
I'm sure you all hear the gripes about the ML JAR being a hefty download. Right now Elasticsearch developers incur a 350MB download at least once a day (or whenever the latest SNAPSHOT changes). Some folks survive with less than ideal internet access and when S3 is acting wonky this slows everyone down.

The _vast_ majority of this artifact is dependent libraries which rarely change. One thought is to publish separate artifacts, one with just the ML code (ml-nodeps) and another with just the dependencies (ml-deps), the current distribution could remain (or become ml-full). The idea here being that the dependencies artifact would change infrequently so the locally cached artifact could be reused more often than not, with only the `-nodeps` artifact needing to be redownloaded. Gradle handles this for us by doing HEAD requests on artifacts to see if they have changed, if not, use the locally cached one. This saves us downloading a few hundred megs of native binaries because of a single change in the `ml-cpp` repo. Thoughts?

**Comment by droberts195** [comment]
> One thought is to publish separate artifacts, one with just the ML code (ml-nodeps) and another with just the dependencies (ml-deps)

Yes, that sounds like a good idea.

In the ml-cpp build we'll need some way to decide whether to upload a new "deps" artifact after each build.  I think this means we'll finally have to add some metadata.  The metadata for the "deps" artifact can list the names and sizes or checksums of all the files in the zip.  Then if the existing metadata file is identical to the newly generated one we won't upload the "deps" artifact.  I don't think we can literally diff the zip files because the old and new zips could contain the same files in a different order.

So generating this metadata is the next step.  Do you know of an off-the-shelf component that we could use?

**Comment by droberts195** [comment]
> [Gradle has support for creating reproducible archives](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/bundling/AbstractArchiveTask.html#setReproducibleFileOrder-boolean-) so each build would produce the same hash.

That sounds perfect.  In that case it shouldn't be very hard to produce two extra zip files for each build.  I'll give it a try.

**Comment by mark-vieira** [comment]
>  I'll give it a try.

Don't hesitate to reach out if you need assistance here.

**Comment by droberts195** [comment]
In #2163 I've made a change to generate the split artifacts, but testing this showed there's _something_ throttling downloads from S3 to my Mac.  I guess the equivalent is what's happening to a lot of people recently.

These files are from the test on my Mac:

```
bash-3.2$ ls -l distributions/
total 2198416
-rw-rw-r--  1 dave  dev   24214313 Dec 21 13:20 ml-cpp-8.1.0-SNAPSHOT-darwin-aarch64.zip
-rw-rw-r--  1 dave  dev   44677506 Dec 21 13:25 ml-cpp-8.1.0-SNAPSHOT-darwin-x86_64.zip
-rw-rw-r--  1 dave  dev   40687997 Dec 21 13:29 ml-cpp-8.1.0-SNAPSHOT-linux-aarch64.zip
-rw-rw-r--  1 dave  dev  224706287 Dec 21 14:04 ml-cpp-8.1.0-SNAPSHOT-linux-x86_64.zip
-rw-rw-r--  1 dave  dev   32466365 Dec 21 14:09 ml-cpp-8.1.0-SNAPSHOT-windows-x86_64.zip
-rw-rw-r--  1 dave  dev  368426380 Dec 21 14:10 ml-cpp-8.1.0-SNAPSHOT.zip
-rw-rw-r--  1 dave  dev  326889036 Dec 21 14:10 ml-cpp-deps-8.1.0-SNAPSHOT.zip
-rw-rw-r--  1 dave  dev   41539498 Dec 21 14:10 ml-cpp-nodeps-8.1.0-SNAPSHOT.zip
```

The top 5 were downloaded from S3 in about 50 minutes.  The bottom 3 were then created locally by Gradle by combining the ones that were downloaded (with filtering in the case of the bottom 2).

Then this is the same on a Linux machine in the London office:

```
[dave@marple build]$ ls -l distributions/
total 1077752
-rw-rw-r--. 1 dave dev  24214313 Dec 21 14:49 ml-cpp-8.1.0-SNAPSHOT-darwin-aarch64.zip
-rw-rw-r--. 1 dave dev  44677506 Dec 21 14:49 ml-cpp-8.1.0-SNAPSHOT-darwin-x86_64.zip
-rw-rw-r--. 1 dave dev  40687997 Dec 21 14:49 ml-cpp-8.1.0-SNAPSHOT-linux-aarch64.zip
-rw-rw-r--. 1 dave dev 224706287 Dec 21 14:50 ml-cpp-8.1.0-SNAPSHOT-linux-x86_64.zip
-rw-rw-r--. 1 dave dev  32466365 Dec 21 14:50 ml-cpp-8.1.0-SNAPSHOT-windows-x86_64.zip
-rw-rw-r--. 1 dave dev 368426380 Dec 21 14:51 ml-cpp-8.1.0-SNAPSHOT.zip
-rw-rw-r--. 1 dave dev 326889036 Dec 21 14:52 ml-cpp-deps-8.1.0-SNAPSHOT.zip
-rw-rw-r--. 1 dave dev  41539498 Dec 21 14:52 ml-cpp-nodeps-8.1.0-SNAPSHOT.zip
```

That managed to do the downloads from S3 in 1 minute rather than 50.  The London office internet is _much_ faster than mine, but still, it shouldn't take me 50 minutes to download 368MB - that works out at about 1Mbps.  I generally get about 35-36Mbps according to [speedtest.net](https://speedtest.net).  So there's something throttling the download speed from S3 when downloading to my Mac (and presumably other people's Macs too).

It will still be beneficial to cut the size people regularly download from 368MB to 41MB, but I'm thinking there's also something else at play here that's made the download speed even worse than it should be recently.

**Comment by mark-vieira** [comment]
> It will still be beneficial to cut the size people regularly download from 368MB to 41MB, but I'm thinking there's also something else at play here that's made the download speed even worse than it should be recently.

Yes, many folks have been experiencing this as well. This effort is worthwhile either way since at 368M on a 10Mbit connection you're looking at a 5 minute download. Thanks, Dave!
