### ISSUE TITLE
[ML] PR builds for 8.8 and 7.17 don't work on ARM macOS

### ISSUE THREAD

**Issue by droberts195** [elastic/ml-cpp#2492]
The ARM macOS build for #2490 failed with this error:

```
.buildkite/scripts/steps/build_and_test.sh
/buildkite/builds/bk-agent-elastic-k8s-1684436186668993914/elastic/ml-cpp/dev-tools/docker/docker_entrypoint.sh: line 35: cmake: command not found
🚨 Error: The command exited with status 127
user command error: exit status 127
```

There's a bug here because we shouldn't be trying to build in Docker on native macOS.

Full build log is https://buildkite.com/elastic/ml-cpp/builds/604.

The ARM macOS build for #2491 failed with this error:

```
./3rd_party.sh --add /buildkite/builds/bk-agent-elastic-k8s-1684436496107449095/elastic/ml-cpp/build/distribution/platform/linux-x86_64/lib
mkdir -p /buildkite/builds/bk-agent-elastic-k8s-1684436496107449095/elastic/ml-cpp/build/distribution/platform/linux-x86_64/..
...
ls: cannot access '/usr/local/gcc75/lib/*boost*gcc*mt-x64-1_71.so.1.71.0': No such file or directory
Boost libraries not found
make[1]: *** [Makefile:21: install] Error 5
make[1]: Leaving directory '/buildkite/builds/bk-agent-elastic-k8s-1684436496107449095/elastic/ml-cpp/3rd_party'
make: *** [/buildkite/builds/bk-agent-elastic-k8s-1684436496107449095/elastic/ml-cpp/mk/toplevel.mk:31: all] Error 1
🚨 Error: The command exited with status 2
user command error: exit status 2
```

This appears to be attempting to do the Linux build on macOS.

Full build log is https://buildkite.com/elastic/ml-cpp/builds/605.

**Comment by edsavage** [comment]
Initial assessment of both of the macOS build failures is that the builds were incorrectly assigned to a kubernetes build agent (`bk-agent-elastic-k8s-1684436186668993914` for the 8.8 build, `bk-agent-elastic-k8s-1684436496107449095` for the 7.17 build) instead of being queued for the native mac worker `worker-h2wdt2qxq6ny.build.macstadium.elasticnet.co`. The modes of failure for the two builds are different since one uses `cmake` and the other simply `make`.

My suspicion is that native macOS builds aren't being queued correctly if the worker is busy but are instead being palmed off to a generic kubernetes worker. Some investigation is required to confirm this.

**Comment by edsavage** [comment]
Confirmed that there's nothing inherently wrong or special about macOS aarch 64 native builds on the 8.8 and 7.17 branches. When run in isolation the builds pass, see:

https://buildkite.com/elastic/ml-cpp/builds/619#01885794-ed43-49b1-a249-38d0de05b329 (8.8) and
https://buildkite.com/elastic/ml-cpp/builds/620#0188577f-90c1-4387-9600-553a8190bbb0 (7.17)

However, as suspected, a macOS aarch 64 native build will fail (on _any_ branch) if there is already another such build in progress, due to being assigned (incorrectly) to a kubernetes worker instead of being queued until the mac stadium worker is available.

**Comment by droberts195** [comment]
This was fixed in the CI infra.
