### ISSUE TITLE
`CStringStore` Unit tests write way too many logs

### ISSUE THREAD

**Issue by benwtrent** [elastic/ml-cpp#302]
CStringStore unit tests write thousands of logs like the following: 

```
2018-11-02 15:49:24,988 UTC [3922] ERROR CBucketGatherer.cc@451 Sample start time 166605000 is not bucket aligned
2018-11-02 15:49:24,988 UTC [3922] ERROR CBucketGatherer.cc@451 Sample start time 166605000 is not bucket aligned
2018-11-02 15:49:24,988 UTC [3922] ERROR CBucketGatherer.cc@451 Sample start time 166605000 is not bucket aligned
2018-11-02 15:49:24,988 UTC [3922] ERROR CBucketGatherer.cc@451 Sample start time 166615000 is not bucket aligned
2018-11-02 15:49:24,988 UTC [3922] ERROR CBucketGatherer.cc@451 Sample start time 166615000 is not bucket aligned
```

We need to either fix the test or mute these particular logs when being ran from a unittest.

**Comment by benwtrent** [comment]
Found the path that is causing this:

In all of the tests a non-zero bucket delay is added: https://github.com/elastic/ml-cpp/blob/0328bdb64942271b17986f2755020ed676bce06a/lib/api/unittest/CStringStoreTest.cc#L131

This trips this conditional: https://github.com/elastic/ml-cpp/blob/0328bdb64942271b17986f2755020ed676bce06a/lib/model/CAnomalyDetector.cc#L370-L372

Which cuts the bucketLength in half. Then the following start/ends are off by half a bucket length and when:

https://github.com/elastic/ml-cpp/blob/0328bdb64942271b17986f2755020ed676bce06a/lib/model/CAnomalyDetector.cc#L388-L390 

https://github.com/elastic/ml-cpp/blob/0328bdb64942271b17986f2755020ed676bce06a/lib/model/CAnomalyDetector.cc#L398-L400

is called, certain models validate the sample times

e.g `CCountingModel::sample`, 

https://github.com/elastic/ml-cpp/blob/4dd90fa93338667b681364657222715f81c9868a/lib/model/CCountingModel.cc#L210-L219

Which calls:

https://github.com/elastic/ml-cpp/blob/0328bdb64942271b17986f2755020ed676bce06a/lib/model/CBucketGatherer.cc#L450-L453

I can make this stop by having CStringStoreTest not set the bucketDelay and let it use the default of 0. 

What say y'all @tveasey @droberts195 ?

**Comment by droberts195** [comment]
`bucketDelay` corresponds to the config option `result_finalization_window`, and we still have that in our Java side `AnalysisConfig` objects.  What happens in the test makes me think that if anyone ever set that to a non-zero value then we could get this problem in production.

We need to check the code in more detail, so don't make any changes today, but since we do little/no testing with non-zero `result_finalization_window`s I'm wondering if we should remove all trace of it from the product.

**Comment by droberts195** [comment]
`result_finalization_window` is undocumented in our [public analysis config documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-job-resource.html#ml-analysisconfig).  Now we have our multi-bucket feature it's unlikely we'd ever want to resurrect the old Prelert attempt at multiple bucket lengths, and, if I remember correctly, `result_finalization_window` was designed to work with that.

Based on this issue there's clearly a bug that's triggered if this option is used.  Since it's undocumented my preference would be to change the code to completely remove it in 6.6.

But before this is done, can you think of any reason to keep `result_finalization_window` aka `bucketResultsDelay` @tveasey and @dimitris-athanasiou?

**Comment by tveasey** [comment]
This was also for implementing out-of-phase analysis to mitigate bucketing effects partially sampling important features in the time series.

However, I don't think that this is something we are going to prioritise reviving. I'm not sure it is worth the complexity and there is functionality overlap the new multi-bucket functionality.

Removing this also means we don't need result serialisation and various other code. I'd be +1 for cleaning this up now, especially since it appears to not be working correctly.
