### ISSUE TITLE
[ML] Spurious anomalies after stopping to receive data for a partition in realtime operation

### ISSUE THREAD

**Issue by tveasey** [elastic/ml-cpp#305]
We've had a number of cases reported with very similar apparent cause and effect:
1. Running in realtime
2. Partitioned analysis
3. One (or more) partitions stop receiving data
4. Anomalies start to appear for the partitions in 3 long after they stop getting data

Running the same analysis on the same data set in look back also doesn't appear to show the problem. The only difference in these two modes of operation is additional control messages passed from Java to the autodetect process.

We need to work out how to reproduce and debug any differences in the model versus look back on identical data (since the actual alerts typically don't appear to start for weeks after the data ends).

**Comment by droberts195** [comment]
This is still being seen in 7.7.1.

**Comment by droberts195** [comment]
Apparently this is fixed by #1158, which is in 7.8.0.  However, for a job where the problem has already occurred an upgrade to 7.8 will not immediately fix the problem.  The model will gradually improve after upgrade such that actual = 0, typical = 0 for a partition seeing no data does not incorrectly raise an anomaly.

**Comment by tveasey** [comment]
This should have been closed when merging #1158 which fixed an example of this that I managed to reproduce and the most likely cause.
