### ISSUE TITLE
[ML] Migrate boost functionality to std alternatives

### ISSUE THREAD

**Issue by tveasey** [elastic/ml-cpp#337]
We have some more functionality we can migrate on master from boost to std:
- [x] boost::array
- [ ] boost::size
- [x] boost::begin, boost::end (boost/range.hpp)
- [x] boost::is_pod
- [x] boost::ref, boost::cref, etc (boost/ref.hpp)
- [x] boost::make_unique
- [x] boost::algorithm::is_sorted
- [x] boost::bind

**Comment by droberts195** [comment]
The branches have moved on since this issue was first raised, so the changes made should not just go into master but should also be backported to 7.x now.

**Comment by mlocs** [comment]
There is a problem with moving from boost::ref to std:: ref since our code often uses boost::unwrap_reference while std::unwrap_reference is only implemented in c++20.

**Comment by droberts195** [comment]
Yes, good point about `unwrap_reference`.  Let's stick with `boost::ref` for the time being then.

**Comment by mlocs** [comment]
I have to fix it in some places, since std::bind doesn't work good with `boost::ref`, but does with `std::ref`, but I leave it in the files where `boost::unwrap_references` is used and hence the simple change is impossible.

**Comment by droberts195** [comment]
> but I leave it in the files where `boost::unwrap_references` is used

This sounds error prone to me.

My preference was always that for each class that exists in both `std` and `boost` we consistently use one or the other throughout the entire codebase.  This then works nicely with the way we name types.  Once you learn the naming convention you know that `TStrCRef` is a `reference_wrapper<const std::string>`.  And whether that's `std::reference_wrapper<const std::string>` or `boost::reference_wrapper<const std::string>` doesn't matter _as long as we're using the same one throughout the codebase_.  As soon as `TStrCRef` means `std::reference_wrapper<const std::string>` in some files and `boost::reference_wrapper<const std::string>` in other files the naming convention becomes a hinderance rather than a help.

So I would prefer that we do one of the following:

1. Leave all uses of `ref`, `cref`, `unwrap_ref` and `bind` as the `boost` versions until `std::unwrap_ref` is available
_or_
2. Add a file like `include/core/UnwrapRef.h` that implements `ml::core::unwrap_ref`.  Then the `boost::unwrap_ref` calls in our code can be replaced with `core::unwrap_ref` now, and then when when all our compilers support `std::unwrap_ref` it will be another simple search and replace of `core::unwrap_ref` with `std::unwrap_ref`.  I think the code contents of `include/core/UnwrapRef.h` will be something like this:

```
namespace ml {
namespace core {

template <typename T>
struct unwrap_reference {
    typedef T type;
};

template <typename T>
struct unwrap_reference<std::reference_wrapper<T>> {
    typedef T type;
};

template <typename T>
struct unwrap_reference<const std::reference_wrapper<T>>{
    typedef T type;
};

template <typename T>
struct unwrap_reference<volatile std::reference_wrapper<T>> {
    typedef T type;
};

template <typename T>
typename unwrap_reference<T>::type& unwrap_ref(T& t) {
    return t;
}
}
}
```

(plus the usual copyright header, include guards and a Doxygen comment saying that the names don't conform to our coding standards because we want to ease the transition to `std` when available)

**Comment by droberts195** [comment]
Oh, and sorry this is turning into a complicated project - I thought it was going to be a simple search and replace job 😄

**Comment by mlocs** [comment]
Good idea, I was struggling with the inconsistency myself. I would go with the option 2 since it reduces more of the technical debt.

**Comment by mlocs** [comment]
std::size() is only supported since c++17
