### ISSUE TITLE
Upgrade our libexpat library

### ISSUE THREAD

**Issue by joshbressers** [elastic/ml-cpp#728]
We ship version 2.2.6 of libexpat with ml. There are two minor security issues fixed in newer versions. I don't believe we pass untrusted input to libexpat, however we should consider upgrading this library. These CVE IDs are showing up on automated security scanners.

**[CVE-2019-15903](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-15903)**
In libexpat before 2.2.8, crafted XML input could  fool the parser into changing from DTD parsing to document parsing too  early; a consecutive call to XML_GetCurrentLineNumber (or  XML_GetCurrentColumnNumber) then resulted in a heap-based buffer  over-read.

**[CVE-2018-20843](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-20843)**
In libexpat in Expat before 2.2.7, XML input  including XML names that contain a large number of colons could make the  XML parser consume a high amount of RAM and CPU resources while  processing (enough to be usable for denial-of-service attacks).

**Comment by droberts195** [comment]
Expat is completely removed in 7.5.0, together with log4cxx and the APR family of libraries - see #655.

I agree we won’t pass untrusted input to expat in earlier versions, at least not in the production setup. The only place that expat was used (very indirectly) was via the option to configure log4cxx using an XML config file. But we never do that when ML is used as part of Elasticsearch. In the production setup log4cxx is configured programmatically within the code.

**Comment by droberts195** [comment]
7.5.0 is now GA.  Anybody who is worried about CVEs in Expat should upgrade to 7.5.0 or above. I do not believe it was possible to exploit these CVEs in a standard Elasticsearch installation, so I do not believe it is critical to upgrade.  So the reason to upgrade due to these CVEs is more likely to avoid having to follow a process to obtain an exception or special approval to use a library with a CVE against it.
