### ISSUE TITLE
[ML] Different job results in 6.2.4 and 6.3.0

### ISSUE THREAD

**Issue by pheyos** [elastic/ml-cpp#75]
**Compared versions**
- 6.2.4
- 6.3.0-bc1

**Used datasets and configs**
Single metric job:
- farequote dataset
- mean(responsetime)
- bucket span: 15m

Multi metric job:
- cloudwatch dataset
- mean(CPUUtilization) partition_field_name=instance
- sum(NetworkOut) partition_field_name=instance
- bucket span: 15m

**Results**
Single metric job:
- ![farequote_624_vs_630](https://user-images.githubusercontent.com/1945390/39303753-a69e595e-4957-11e8-9fa3-84941b52c7ff.png)

Multi metric job:
- ![clodwatch_624_vs_630](https://user-images.githubusercontent.com/1945390/39303759-abef8e32-4957-11e8-99f6-1cb8b9b74289.png)
- ![cloudwatch_region_624_vs_630](https://user-images.githubusercontent.com/1945390/39303769-b1fbee60-4957-11e8-95cb-31a7137dce60.png)

**Comment by pheyos** [comment]
Taken over from the kibana repo (https://github.com/elastic/kibana/issues/18601).

**Comment by tveasey** [comment]
The farequote difference is caused by us detecting daily periodicity in the low resolution test for long periodic components. In fact, there is a periodicity in this data set, but the amplitude is small w.r.t. the noise. In this case, because we have a high resolution test testing (and rejecting) daily periodicity there is no need to run these extra tests. Excluding them we revert to the old behaviour:

![screen shot 2018-04-27 at 15 30 45](https://user-images.githubusercontent.com/7591487/39367910-0add3240-4a30-11e8-825f-d75b74f28f2d.png)

**Comment by tveasey** [comment]
The main issue was farequote regression which was fixed.
