### ISSUE TITLE
Valgrind memcheck errors and warnings

### ISSUE THREAD

**Issue by edsavage** [elastic/ml-cpp#922]
A number of errors and warnings have been picked up by running all the unit tests (apart from those for `seccomp`) under `valgrind --tool=memcheck` .

Log files attached (or soon will be!)

**Comment by edsavage** [comment]
Valgrind log files..


[marple.zip](https://github.com/elastic/ml-cpp/files/4047000/marple.zip)

**Comment by edsavage** [comment]
I think the better way forward with this is to create multiple GitHub entries, one for each `ml-cpp` library (apart from `seccomp`, `seccomp` doesn't play well with `memcheck`. I'll leave this ticket open and use it to track the sub tickets (when created).

**Comment by droberts195** [comment]
Looks like all the real problems are in the `maths` library except for one memory leak in `CTokenListDataCategorizerTest::(anonymous namespace)::checkMemoryUsageInstrumentation` in the `model` library.  I will have a look at the memory leak since it's a test I recently wrote.

(It looks like all the `Leak_PossiblyLost` problems are due to one-off allocations in system libraries that we cannot control, so I am ignoring those.)

**Comment by tveasey** [comment]
Can you post the commit this was created from Ed.

**Comment by tveasey** [comment]
Note that the "Uninitialised value was created by a heap allocation" is probably being generated by not initialising values in `CBoostedTreeHyperparameters` in the default constructor. This is harmless given the usage, but we should zero initialise them.

**Comment by edsavage** [comment]
Will do

**Comment by droberts195** [comment]
All the issues that were found have now been fixed - there was one more in #1445 - so I think this can be closed now.
